src/Entity/Abonnement.php
<?php

namespace App\Entity;

use App\Repository\AbonnementRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=AbonnementRepository::class)
 */
class Abonnement
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=AbonnementDisponible::class, inversedBy="abonnements")
     */
    private $AbonnementDisponible;

    /**
     * @ORM\ManyToOne(targetEntity=User::class)
     */
    private $User;

    /**
     * @ORM\Column(type="date")
     */
    private $date_debut;

    /**
     * @ORM\Column(type="date")
     */
    private $date_fin;

    /**
     * @ORM\Column(type="integer")
     */
    private $tel;

    /**
     * @ORM\Column(type="float")
     */
    private $prix;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getAbonnementDisponible(): ?AbonnementDisponible
    {
        return $this->AbonnementDisponible;
    }

    public function setAbonnementDisponible(?AbonnementDisponible $AbonnementDisponible): self
    {
        $this->AbonnementDisponible = $AbonnementDisponible;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->User;
    }

    public function setUser(?User $User): self
    {
        $this->User = $User;

        return $this;
    }

    public function getDateDebut(): ?\DateTimeInterface
    {
        return $this->date_debut;
    }

    public function setDateDebut(\DateTimeInterface $date_debut): self
    {
        $this->date_debut = $date_debut;

        return $this;
    }

    public function getDateFin(): ?\DateTimeInterface
    {
        return $this->date_fin;
    }

    public function setDateFin(\DateTimeInterface $date_fin): self
    {
        $this->date_fin = $date_fin;

        return $this;
    }

    public function getTel(): ?int
    {
        return $this->tel;
    }

    public function setTel(int $tel): self
    {
        $this->tel = $tel;

        return $this;
    }

    public function getPrix(): ?float
    {
        return $this->prix;
    }

    public function setPrix(float $prix): self
    {
        $this->prix = $prix;

        return $this;
    }
}

src/Controller/ClientAbonneeController.php
<?php

namespace App\Controller;

use App\Entity\Abonnement;
use App\Entity\AbonnementDisponible;
use App\Repository\AbonnementDisponibleRepository;
use App\Repository\AbonnementRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/admin")
 */
class ClientAbonneeController extends AbstractController
{
    /**
     * @Route("/abonnement_client", name="clients_abonnee_back")
     */
    public function index(AbonnementRepository $abonn_repo): Response
    {
        return $this->render('client_abonnee/index.html.twig', [
            'clients_abonnee' => $abonn_repo->findAll()
        ]);
    }

    /**
     * @Route("/abonnement_client/edit/{id}", name="clients_abonnee_back_edit")
     */
    public function edit(Request $request, Abonnement $abonn)
    {
        if ($request->isMethod("POST")) {
            $tel = $request->request->get("tel");
            $abonn->setTel($tel);
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($abonn);
            $entityManager->flush();
            $this->addFlash(
                'success',
                "L'abonnement à été modifié avec succés !"
            );
            return $this->redirectToRoute("clients_abonnee_back");
        }
        return $this->render("client_abonnee/edit.html.twig", [
            'abonn' => $abonn,
        ]);
    }

    /**
     * @Route("/abonnement_client/delete/{id}", name="clients_abonnee_back_delete")
     */
    public function delete(Abonnement $abonn)
    {
        $entityManager = $this->getDoctrine()->getManager();
        $entityManager->remove($abonn);
        $entityManager->flush();
        $this->addFlash(
            'success',
            "L'abonnement à été supprimé avec succés !"
        );
        return $this->redirectToRoute("clients_abonnee_back");
    }
}

templates/client_abonnee/edit.html.twig
{% extends "dashboard.html.twig" %}


{% block body %}

    <div class="text-left">
        <form method="POST" action="/admin/abonnement_client/edit/{{ abonn.id }}">
            <div class="mb-3">
                <label for="tel" class="form-label">Téléphone</label>
                <input type="text" class="form-control" id="tel" name="tel" value="{{ abonn.tel }}">
            </div>
            <button type="submit" class="btn btn-primary">Modifier</button>
        </form>
    </div>

{% endblock %}

templates/client_abonnee/index.html.twig
{% extends "dashboard.html.twig" %}

{% block body %}

    {% for msg in app.flashes('success') %}
        <div class="alert alert-success alert-dismissible fade show" role="alert">
            {{ msg }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>

        </div>
    {% endfor %}

    <div class="wrapper">
        <h3>Liste des clients abonnés</h3>

    </div>

    <table class="table table-bordered table-striped">
        <thead>
        <tr>
            <th scope="col">ID</th>
            <th scope="col">Nom Client</th>
            <th scope="col">Téléphone</th>
            <th scope="col">Description Abonnement</th>
            <th scope="col">Type Abonnement</th>
            <th scope="col">Date Début</th>
            <th scope="col">Date Fin</th>
            <th scope="col">Actions</th>
        </tr>
        </thead>
        <tbody>
        {% for clients_abonnee in clients_abonnee %}
            <tr>
                <td>{{ clients_abonnee.id }}</td>
                <td>{{ clients_abonnee.user.nom }}</td>
                <td>{{ clients_abonnee.tel }}</td>
                <td>{{ clients_abonnee.abonnementDisponible.type }}</td>
                <td>{{ clients_abonnee.abonnementDisponible.descr }}</td>
                <td>{{ clients_abonnee.dateDebut|date('d-m-Y') }}</td>
                <td>{{ clients_abonnee.dateFin|date('d-m-Y') }}</td>
                <td>
                    <a href="{{ path('clients_abonnee_back_edit', {'id': clients_abonnee.id}) }}" class="btn btn-warning btn-sm mr-1 text-light">Modifier</a>
                    <a href="{{ path('clients_abonnee_back_delete', {'id': clients_abonnee.id}) }}" class="btn btn-danger btn-sm text-light" onclick="return confirm('Vous voulez vraiment le supprimer ?');">Supprimer</a>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

{% endblock %}


{% block stylesheets %}

    <style>
        .wrapper {
            display: flex;
            flex-direction: row;
            justify-content: space-between;
            align-items: center;
            margin-bottom: 20px;
        }
    </style>

{% endblock %}