src/Entity/Depot.php
<?php

namespace App\Entity;

use App\Repository\DepotRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity(repositoryClass=DepotRepository::class)
 */
class Depot
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer")
     * @Assert\NotBlank(message="Capacité is required")
     */
    private $Capacite;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Catégorie is required")
     */
    private $Categorie;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Localisation is required")
     */
    private $Localisation;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Etat is required")
     */
    private $Etat;

    /**
     * @ORM\OneToMany(targetEntity=MoyenDeTransport::class, mappedBy="depot")
     */
    private $MoyenDeTransport;

    public function __construct()
    {
        $this->MoyenDeTransport = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCapacite(): ?int
    {
        return $this->Capacite;
    }

    public function setCapacite(int $Capacite): self
    {
        $this->Capacite = $Capacite;

        return $this;
    }

    public function getCategorie(): ?string
    {
        return $this->Categorie;
    }

    public function setCategorie(string $Categorie): self
    {
        $this->Categorie = $Categorie;

        return $this;
    }

    public function getLocalisation(): ?string
    {
        return $this->Localisation;
    }

    public function setLocalisation(string $Localisation): self
    {
        $this->Localisation = $Localisation;

        return $this;
    }

    public function getEtat(): ?string
    {
        return $this->Etat;
    }

    public function setEtat(string $Etat): self
    {
        $this->Etat = $Etat;

        return $this;
    }

    /**
     * @return Collection|MoyenDeTransport[]
     */
    public function getMoyenDeTransport(): Collection
    {
        return $this->MoyenDeTransport;
    }

    public function addMoyenDeTransport(MoyenDeTransport $moyenDeTransport): self
    {
        if (!$this->MoyenDETransport->contains($moyenDeTransport)) {
            $this->MoyenDeTransport[] = $moyenDeTransport;
            $moyenDeTransport->setDepot($this);
        }

        return $this;
    }

    public function removeMoyenDeTransport(MoyenDeTransport $moyenDeTransport): self
    {
        if ($this->MoyenDeTransport->removeElement($moyenDeTransport)) {
            // set the owning side to null (unless already changed)
            if ($moyenDeTransport->getDepot() === $this) {
                $moyenDeTransport->setDepot(null);
            }
        }

        return $this;
    }

    public function __toString(){
        // to show the name of the Category in the select
        return (string)$this->getId();
        // to show the id of the Category in the select
        // return $this->id;
    }
}

src/Controller/Reservation2Controller.php
<?php

namespace App\Controller;
use App\Entity\MoyTransport;
use Dompdf\Dompdf;
use Dompdf\Options;
use App\Entity\Reservation;
use App\Form\Reservation1Type;
use App\Repository\ReservationRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/reservation2")
 */
class Reservation2Controller extends AbstractController
{
    /**
     * @Route("/", name="reservation2_index", methods={"GET"})
     */
    public function index(ReservationRepository $reservationRepository): Response
    {
        return $this->render('reservation2/index.html.twig', [
            'reservations' => $reservationRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="reservation2_new", methods={"GET", "POST"})
     */
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $reservation = new Reservation();
        $form = $this->createForm(Reservation1Type::class, $reservation);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($reservation);
            $entityManager->flush();

            return $this->redirectToRoute('reservation2_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('reservation2/_form.html.twig', [
            '$reservation' => $reservation,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="reservation2_show", methods={"GET"})
     */
    public function show(Reservation $reservation): Response
    {
        return $this->render('reservation2/show.html.twig', [
            'reservation' => $reservation,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="reservation2_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, Reservation $reservation, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(Reservation1Type::class, $reservation);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('reservation2_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('reservation2/edit.html.twig', [
            'reservation' => $reservation,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="reservation2_delete", methods={"POST"})
     */
    public function delete(Request $request, Reservation $reservation, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete' . $reservation->getId(), $request->request->get('_token'))) {
            $entityManager->remove($reservation);
            $entityManager->flush();
        }

        return $this->redirectToRoute('reservation2_index', [], Response::HTTP_SEE_OTHER);
    }


    /**
     * @Route("pdf/", name="reservation2_pdf")
     * @param ReservationRepository $reservationRepository
     */

    public function pdf(ReservationRepository $reservationRepository)
    {

        $pdfOptions = new Options();
        $pdfOptions->set('defaultFont', 'Arial');

        // Instantiate Dompdf with our options
        $dompdf = new Dompdf($pdfOptions);
        $reservation = $reservationRepository->findAll();
        // Retrieve the HTML generated in our twig file
        $html = $this->renderView('reservation2/pdf.html.twig', [
            'reservations' => $reservation,
        ]);


        // Load HTML to Dompdf
        $dompdf->loadHtml($html);

        // (Optional) Setup the paper size and orientation 'portrait' or 'portrait'
        $dompdf->setPaper('A4', 'portrait');

        // Render the HTML as PDF
        $dompdf->render();

        // Output the generated PDF to Browser (force download)
        $dompdf->stream("mypdf.pdf", ["Attachment" => true]);


    }
}

templates/reservation2/_delete_form.html.twig
<form method="post" action="{{ path('reservation2_delete', {'id': reservation.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ reservation.id) }}">
    <button class="btn">Delete</button>
</form>

templates/reservation2/_form.html.twig
{% extends 'dashboard.html.twig' %}
{% block body %}
    {% form_theme form 'bootstrap_4_horizontal_layout.html.twig' %}
    {{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
    {{ form_end(form) }}
{% endblock %}

templates/reservation2/edit.html.twig
{% extends 'dashboard.html.twig' %}

{% block title %}Edit Reservation{% endblock %}

{% block body %}
    <h1>Edit Reservation</h1>

    {{ include('reservation2/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('reservation2_index') }}">back to list</a>

    {{ include('reservation2/_delete_form.html.twig') }}
{% endblock %}

templates/reservation2/index.html.twig
{% extends 'dashboard.html.twig' %}

{% block title %}Reservation index{% endblock %}


{% block body %}
<input type="text" id="search" class="form-control" placeholder="Search">
<section class="jumbotron text-center">
    <div class="container">

        <h1>Reservation index</h1>

        <script src="{{ asset('js/jquery.min.js') }}"></script>
        <table id="tableac" class="table table-striped table-advance table-hover">
            <thead>
            <tr>
                <th>Id</th>
                <th>Iduser</th>
                <th>Date</th>
                <th>Ref</th>
                <th>Etat</th>
                <th>Price</th>
                <th>Name</th>
                <th>actions</th>
            </tr>
            </thead>
            <tbody>
            {% for reservation in reservations %}
                <tr>
                    <td>{{ reservation.id }}</td>
                    <td>{{ reservation.iduser }}</td>
                    <td>{{ reservation.date ? reservation.date|date('Y-m-d') : '' }}</td>
                    <td>{{ reservation.ref }}</td>
                    <td>{{ reservation.etat }}</td>
                    <td>{{ reservation.price }}</td>
                    <td>{{ reservation.name }}</td>
                    <td>
                        <a href="{{ path('reservation2_show', {'id': reservation.id}) }}">show</a>
                        <a href="{{ path('reservation2_edit', {'id': reservation.id}) }}">edit</a>
                    </td>
                </tr>
            {% else %}
                <tr>
                    <td colspan="8">no records found</td>
                </tr>
            {% endfor %}
            <script>
                $(document).ready(function(){
                    $('#search').keyup(function(){
                        search_table($(this).val());
                    });
                    function search_table(value){
                        $('#tableac tbody tr').each(function(){
                            var found = 'false';
                            $(this).each(function(){
                                if($(this).text().toLowerCase().indexOf(value.toLowerCase()) >= 0)
                                {
                                    found = 'true';
                                }
                            });
                            if(found == 'true')
                            {
                                $(this).show();

                            }
                            else
                            {
                                $(this).hide();

                            }
                        });
                    }
                });
            </script>
            </tbody>
        </table>
        <a href="{{ path('reservation2_pdf') }}">Reservation pdf</a>
        {% endblock %}

    </div>
</section>

templates/reservation2/pdf.html.twig
{% block body %}

    <h1 align="center">Riservation</h1>

    {% for reservation in reservations %}
        <table class="table">
            <thead>
            <tr>
                <th>Id</th>
                <th>Iduser</th>
                <th>Date</th>
                <th>Ref</th>
                <th>Etat</th>
                <th>Price</th>
                <th>Name</th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <td>{{ reservation.id }}</td>
                <td>{{ reservation.iduser  }}</td>
                <td>{{ reservation.date ? reservation.date|date('Y-m-d') : '' }}</td>
                <td>{{  reservation.ref }}</td>
                <td>{{ reservation.etat }}</td>
                <td>{{ reservation.price }}</td>
                <td>{{ reservation.name }}</td>

            </tr>
            </tbody>
        </table>



    {% endfor %}


{% endblock %}

templates/reservation2/show.html.twig
{% extends 'dashboard.html.twig' %}

{% block title %}Reservation{% endblock %}

{% block body %}
    <h1>Reservation</h1>

    <table class="table">
        <tbody>
        <tr>
            <th>Id</th>
            <td>{{ reservation.id }}</td>
        </tr>
        <tr>
            <th>Iduser</th>
            <td>{{ reservation.iduser }}</td>
        </tr>
        <tr>
            <th>Date</th>
            <td>{{ reservation.date ? reservation.date|date('Y-m-d') : '' }}</td>
        </tr>
        <tr>
            <th>Ref</th>
            <td>{{ reservation.ref }}</td>
        </tr>
        <tr>
            <th>Etat</th>
            <td>{{ reservation.etat }}</td>
        </tr>
        <tr>
            <th>Price</th>
            <td>{{ reservation.price }}</td>
        </tr>
        <tr>
            <th>Name</th>
            <td>{{ reservation.name }}</td>
        </tr>
        </tbody>
    </table>
    <div class="fb-share-button" data-href="http://127.0.0.1:8000/reservation2/{{reservation.id}}/" data-layout="button_count" data-size="large"><a target="_blank" href="https://www.facebook.com/sharer/sharer.php?u=http%3A%2F%2F127.0.0.1%3A8000%2Fform%2Faide%2F10%2F&amp;src=sdkpreparse" class="fb-xfbml-parse-ignore">Share</a></div>
    <a href="{{ path('reservation2_index') }}">back to list</a>

    <a href="{{ path('reservation2_edit', {'id': reservation.id}) }}">edit</a>

    {{ include('reservation2/_delete_form.html.twig') }}
{% endblock %}