src/Entity/Voyage.php
<?php

namespace App\Entity;

use App\Repository\VoyageRepository;
use Doctrine\ORM\Mapping as ORM;

use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;



/**
 * @ORM\Entity(repositoryClass=VoyageRepository::class)
 *
 * @UniqueEntity(
 *     fields={"ref_voyage"},
 *     message="ref_voyage already exist !"
 * )
 */
class Voyage
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=128,unique=true)
     * @Assert\NotBlank(message="ref_voyage is required")
     *
     *
     */
    private $ref_voyage;

    /**
     * @ORM\OneToOne (targetEntity=Station::class)
     * @ORM\JoinColumn(nullable=false,onDelete="CASCADE")
     * @Assert\NotBlank(message="Station is required")
     */
    private $station_depart;

    /**
     * @ORM\OneToOne (targetEntity=Station::class)
     * @ORM\JoinColumn(nullable=false,onDelete="CASCADE")
     * @Assert\NotBlank(message="Station_arrive is required")
     */
    private $Station_arrive;

    /**
     * @ORM\Column(type="array", nullable=true)
     *
     */
    private $ligne = [];

    /**
     * @ORM\OneToOne(targetEntity=MoyenDeTransport::class)
     * @ORM\JoinColumn(nullable=false,onDelete="CASCADE")
     * @Assert\NotBlank(message="MoyenDeTransport is required")
     */
    private $MoyenDeTransport;

    /**
     * @ORM\Column(type="datetime")
     * @Assert\NotBlank(message="date_depart is required")
     */
    private $date_depart;

    /**
     * @ORM\Column(type="datetime")
     * @Assert\NotBlank(message="date_arrive is required")
     */
    private $date_arrive;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getRefVoyage(): ?string
    {
        return $this->ref_voyage;
    }

    public function setRefVoyage(string $ref_voyage): self
    {
        $this->ref_voyage = $ref_voyage;

        return $this;
    }

    public function getStationDepart(): ?Station
    {
        return $this->station_depart;
    }

    public function setStationDepart(Station $station_depart): self
    {
        $this->station_depart = $station_depart;

        return $this;
    }

    public function getStationArrive(): ?Station
    {
        return $this->Station_arrive;
    }

    public function setStationArrive(Station $Station_arrive): self
    {
        $this->Station_arrive = $Station_arrive;

        return $this;
    }

    public function getLigne(): ?array
    {
        return $this->ligne;
    }

    public function setLigne(?array $ligne): self
    {
        $this->ligne = $ligne;

        return $this;
    }

    public function getMoyenDeTransport(): ?MoyenDeTransport
    {
        return $this->MoyenDeTransport;
    }

    public function setMoyenDeTransport(MoyenDeTransport $MoyenDeTransport): self
    {
        $this->MoyenDeTransport = $MoyenDeTransport;

        return $this;
    }

    public function getDateDepart(): ?\DateTimeInterface
    {
        return $this->date_depart;
    }

    public function setDateDepart(\DateTimeInterface $date_depart): self
    {
        $this->date_depart = $date_depart;

        return $this;
    }

    public function getDateArrive(): ?\DateTimeInterface
    {
        return $this->date_arrive;
    }

    public function setDateArrive(\DateTimeInterface $date_arrive): self
    {
        $this->date_arrive = $date_arrive;

        return $this;
    }
}

src/Form/VoyageType.php
<?php

namespace App\Form;

use App\Entity\Voyage;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class VoyageType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('ref_voyage')
            ->add('ligne')
            ->add('date_depart',DateTimeType::class,['widget'=>'single_text'])
            ->add('date_arrive',DateTimeType::class,['widget'=>'single_text'])
            ->add('station_depart')
            ->add('Station_arrive')
            ->add('MoyenDeTransport')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Voyage::class,
        ]);
    }
}

src/Controller/VoyageController.php
<?php

namespace App\Controller;

use App\api\MailerApi;
use App\api\TwilioApi;
use App\Entity\Voyage;
use App\Form\VoyageType;
use App\Repository\VoyageRepository;
use MercurySeries\FlashyBundle\FlashyNotifier;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Mailer\Exception\TransportExceptionInterface;
use Symfony\Component\Mailer\MailerInterface;
use Symfony\Component\Mercure\HubInterface;
use Symfony\Component\Mercure\Update;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\ParamConverter;

/**
 * @Route("/voyage")
 */
class VoyageController extends AbstractController
{
    /**
     * @Route("/", name="voyage_index", methods={"GET"})
     */
    public function index(VoyageRepository $voyageRepository): Response
    {
        return $this->render('voyage/index.html.twig', [
            'voyages' => $voyageRepository->findAll(),
        ]);
    }

    /**
     * @Route("/listVoyages", name="list_voyages", methods={"GET"})
     */
    public function listVoy(VoyageRepository $voyageRepository): Response
    {
        return $this->render('demo/tours/tour-3-columns-video-header/voyageShowCase.html.twig', [
            'voyages' => $voyageRepository->findAll(),
        ]);
    }
    
    /**
     * @Route("/fetch", name="voyage_fetch", methods={"GET"})
     */
    public function fetch(VoyageRepository $voyageRepository): Response
    {
        return $this->render('frontOffice/index-2.html.twig', [
            'voyages' => $voyageRepository->findAll(),

        ]);
    }

    /**
     * @Route("/voyage-detail/{id}", name="voyage_detail", methods={"GET"})
     */
    public function voyageDetail(Voyage $voyage): Response
    {
        return $this->render('demo/tour/french-autumn/detailVoyage.html.twig', [
            'voyage' => $voyage,
        ]);
    }


    /**
     * @Route("/new", name="voyage_new", methods={"GET","POST"})
     * @throws TransportExceptionInterface
     */
    public function new(MailerInterface $mailer,Request $request,FlashyNotifier $flashy): Response
    {
        $voyage = new Voyage();
        $form = $this->createForm(VoyageType::class, $voyage);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($voyage);
            $entityManager->flush();


            $email = new MailerApi();
            $twilio = new TwilioApi('AC827499c505a0825c13b9c15a5e57dcde','f9a23e828a3f17c9441b94a32d1678a3','+14704444081');
            $twilio->sendSMS('+21625892319',"le voyage ayant le code : {$voyage->getRefVoyage()} a été bien ajouté ");
            $email->sendEmail( $mailer,'tunisport32@gmail.com','mouhamedaminerouatbi@gmail.com','testing email',"le voyage ayant le code : {$voyage->getRefVoyage()} a été bien ajouté ");
            $this->addFlash(
                'info' ,' Voyage Ajouté avec success !');

            return $this->redirectToRoute('voyage_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('voyage/new.html.twig', [
            'voyage' => $voyage,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="voyage_show", methods={"GET"})
     */
    public function show(Voyage $voyage): Response
    {
        return $this->render('voyage/show.html.twig', [
            'voyage' => $voyage,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="voyage_edit", methods={"GET","POST"})
     */
    public function edit(MailerInterface $mailer,Request $request, Voyage $voyage,FlashyNotifier $flashy): Response
    {
        $form = $this->createForm(VoyageType::class, $voyage);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            $email = new MailerApi();
            $twilio = new TwilioApi('AC827499c505a0825c13b9c15a5e57dcde','f9a23e828a3f17c9441b94a32d1678a3','+14704444081');
            $twilio->sendSMS('+21625892319',"le voyage ayant le code : {$voyage->getRefVoyage()} a été bien modifié ");
            $email->sendEmail( $mailer,'tunisport32@gmail.com','mouhamedaminerouatbi@gmail.com','testing email',"le voyage ayant le code : {$voyage->getRefVoyage()} a été bien modifié ");
            $this->addFlash(
                'info' ,' voyage Modifier avec success !');


            return $this->redirectToRoute('voyage_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('voyage/edit.html.twig', [
            'voyage' => $voyage,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="voyage_delete", methods={"POST"})
     * @throws TransportExceptionInterface
     */
    public function delete(MailerInterface $mailer,Request $request, Voyage $voyage,FlashyNotifier $flashy): Response
    {
        if ($this->isCsrfTokenValid('delete'.$voyage->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($voyage);
            $entityManager->flush();

            $email = new MailerApi();
            $twilio = new TwilioApi('AC827499c505a0825c13b9c15a5e57dcde','f9a23e828a3f17c9441b94a32d1678a3','+14704444081');
            $twilio->sendSMS('+21625892319',"le voyage ayant le code : {$voyage->getRefVoyage()} a été bien supprimé ");
            $email->sendEmail( $mailer,'tunisport32@gmail.com','mouhamedaminerouatbi@gmail.com','testing email',"le voyage ayant le code : {$voyage->getRefVoyage()} a été bien supprimé ");


            $this->addFlash(
                'info' ,' Voyage  supprimé avec success !');
        }

        return $this->redirectToRoute('voyage_index', [], Response::HTTP_SEE_OTHER);
    }









}

templates/voyage/_delete_form.html.twig
<form method="post" action="{{ path('voyage_delete', {'id': voyage.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ voyage.id) }}">
    <br/>
    <button class="btn btn-dark">Delete</button>
</form>

templates/voyage/_form.html.twig
{% form_theme form 'bootstrap_4_horizontal_layout.html.twig' %}

{{ form_start(form,{'attr':{'novalidate':'novalidate'}}) }}


    {{ form_widget(form) }}




    {{ form_errors(form) }}





    <button class="btn btn-dark">{{ button_label|default('Save') }}</button>
    {{ form_end(form) }}

templates/voyage/edit.html.twig
{% extends 'dashboard.html.twig' %}

{% block title %}Edit Voyage{% endblock %}

{% block body %}
    <h1>Edit Voyage</h1>

    {{ include('voyage/_form.html.twig', {'button_label': 'Update'}) }}
<br/>
    <a class="btn btn-danger" href="{{ path('voyage_index') }}">back to list</a>

    {{ include('voyage/_delete_form.html.twig') }}
{% endblock %}

templates/voyage/getVoyages.html.twig
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

<table class="table">
    <thead>
    <tr>
        <th>Id</th>
        <th>Ref_voyage</th>
        <th>Station_Depart</th>
        <th>Station_Arrive</th>
        <th>Vehicule</th>
        <th>Ligne</th>

        <th>Date_depart</th>
        <th>Date_arrive</th>
        <th>actions</th>
    </tr>
    </thead>
    <tbody>
    {% for voyagee in voyages %}
        <tr>
            <td>{{ voyagee.id }}</td>
            <td>{{ voyagee.refVoyage }}</td>
            <td>{{ voyagee.getStationDepart()}}</td>
            <td>{{ voyagee.getStationArrive()}}</td>
            <td>{{ voyagee.MoyenDeTransport }}</td>
            <td>{{ voyagee.ligne ? voyage.eligne|join(', ') : '' }}</td>
            <td>{{ voyagee.dateDepart ? voyagee.dateDepart|date('Y-m-d H:i:s') : '' }}</td>
            <td>{{ voyagee.dateArrive ? voyagee.dateArrive|date('Y-m-d H:i:s') : '' }}</td>
            <td>
                <a class="btn btn-primary" href="{{ path('voyage_show', {'id': voyagee.id}) }}">show</a>
                <a class="btn btn-danger" href="{{ path('voyage_edit', {'id': voyagee.id}) }}">edit</a>
            </td>
        </tr>
        <div class="card" style="width: 18rem;">
            <div class="card-body">
                <h5 class="card-title">{{ voyagee.id }}</h5>
                <h6 class="card-subtitle mb-2 text-muted">{{ voyagee.getStationDepart() }} --> {{ voyagee.getStationArrive() }}</h6>
                <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                <a href="#" class="card-link">Card link</a>
                <a href="#" class="card-link">Another link</a>
            </div>
        </div>
    {% else %}
        <tr>
            <td colspan="6">no records found</td>
        </tr>
    {% endfor %}


    </tbody>
</table>

</body>
</html>

templates/voyage/index.html.twig
{% extends 'dashboard.html.twig' %}

{% block title %}Voyage index{% endblock %}

{% block body %}
    <h1>Liste Des Voyages</h1>

    <input type="text" id="search" class="form-control" placeholder="Search">

    {% for message in app.flashes('info')  %}
        <div class="alert-success" role="alert">
        {{ message }}
        </div>
    {% endfor%}


    <table id ="tableac" class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Ref_voyage</th>
                <th>Station_Depart</th>
                <th>Station_Arrive</th>
                <th>Vehicule</th>
                <th>Ligne</th>

                <th>Date_depart</th>
                <th>Date_arrive</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for voyage in voyages %}
            <tr>
                <td>{{ voyage.id }}</td>
                <td>{{ voyage.refVoyage }}</td>
                <td>{{ voyage.getStationDepart()}}</td>
                <td>{{ voyage.getStationArrive()}}</td>
                <td>{{ voyage.MoyenDeTransport }}</td>
                <td>{{ voyage.ligne ? voyage.ligne|join(', ') : '' }}</td>
                <td>{{ voyage.dateDepart ? voyage.dateDepart|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ voyage.dateArrive ? voyage.dateArrive|date('Y-m-d H:i:s') : '' }}</td>
                <td>
                    <a class="btn btn-primary" href="{{ path('voyage_show', {'id': voyage.id}) }}">show</a>
                    <a class="btn btn-danger" href="{{ path('voyage_edit', {'id': voyage.id}) }}">edit</a>

                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a class="btn btn-warning" href="{{ path('voyage_new') }}">Create new</a>
{% endblock %}

{% block javascripts %}
    <script>
        $(document).ready(function(){
            $('#search').keyup(function(){
                search_table($(this).val());
            });
            function search_table(value){
                $('#tableac tbody tr').each(function(){
                    var found = 'false';
                    $(this).each(function(){
                        if($(this).text().toLowerCase().indexOf(value.toLowerCase()) >= 0)
                        {
                            found = 'true';
                        }
                    });
                    if(found == 'true')
                    {
                        $(this).show();

                    }
                    else
                    {
                        $(this).hide();

                    }
                });
            }
        });
    </script>
{% endblock %}

templates/voyage/new.html.twig
{% extends 'dashboard.html.twig' %}

{% block title %}New Voyage{% endblock %}

{% block body %}
    <h1>Create new Voyage</h1>

    {{ include('voyage/_form.html.twig') }}

    <br/>
    <a class="btn btn-danger" href="{{ path('voyage_index') }}">back to list</a>
{% endblock %}

templates/voyage/show.html.twig
{% extends 'dashboard.html.twig' %}

{% block title %}Voyage{% endblock %}

{% block body %}
    <h1>Voyage</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ voyage.id }}</td>
            </tr>
            <tr>
                <th>Ref_voyage</th>
                <td>{{ voyage.refVoyage }}</td>
            </tr>
            <tr>
                <th>Ligne</th>
                <td>{{ voyage.ligne ? voyage.ligne|join(', ') : '' }}</td>
            </tr>
            <tr>
                <th>station_depart</th>
                <td>{{ voyage.getStationDepart()}}</td>
            </tr>
            <tr>
                <th>Station_arrive</th>
                <td>{{ voyage.getStationArrive()}}</td>
            </tr>
            <tr>
                <th>Date_depart</th>
                <td>{{ voyage.dateDepart ? voyage.dateDepart|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Date_arrive</th>
                <td>{{ voyage.dateArrive ? voyage.dateArrive|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a class="btn btn-danger" href="{{ path('voyage_index') }}">back to list</a>

    <a class="btn btn-primary" href="{{ path('voyage_edit', {'id': voyage.id}) }}">edit</a>
<br/>
    {{ include('voyage/_delete_form.html.twig') }}
{% endblock %}

templates/voyage/stat.html.twig
{% extends 'dashboard.html.twig' %}

{% block title %} Statistiques{% endblock %}
{% block stylesheets %}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.4/Chart.min.css" integrity="sha512-/zs32ZEJh+/EO2N1b0PEdoA10JkdC3zJ8L5FTiQu82LR9S/rOQNfQN7U59U9BC12swNeRAz3HSzIL2vpp4fv3w==" crossorigin="anonymous" referrerpolicy="no-referrer" />
{% endblock %}
{% block body %}
    <div class="container" style="width:600px !important; height: 480px !important;">
        <h1>Statistiques Pour Le Module Voyage</h1>
        <canvas id="voyages" width="100" height="100" style="margin-top :50px !important;"></canvas>
        <canvas id="stations" width="100" height="100" style="margin-top :50px !important;"></canvas>
        <canvas id="vehicules" width="100" height="100" style="margin-top :50px !important;"></canvas>
    </div>



{% endblock %}
{% block javascripts %}
    <script src="https://cdn.jsdelivr.net/npm/chart.js@3.6.1/dist/chart.min.js"></script>
<script>

    const dates = {{ voyageDateDepart|raw }}
    const newDates = [];
    dates.forEach(date=>{
        newDates.push(date.date.split(" ")[0]);
    })
    const finalDates = [...new Set(newDates)]
    const finalMt = [...new Set({{ voyageMt|raw }})]
    //set the color of bars dynamically
    let backGroundColor = [];
    function getRandomInt(min, max) {
        min = Math.ceil(min);
        max = Math.floor(max);
        return Math.floor(Math.random() * (max - min + 1)) + min;
    }
    //we need to get the exact number of dates
    finalDates.forEach(date=>{
        //set random rgb values for each date
        backGroundColor.push(`rgba(${getRandomInt(1,256)}, ${getRandomInt(1,99)}, ${getRandomInt(1,256)}, 0.2)`)
    })
    let secondChartBackGroundColor = []
    let thirdChartBackGroundColor = []

    let NombreStations = {{ voyageStation|raw }} ;
    NombreStations.forEach(station=>{
        secondChartBackGroundColor.push(`rgba(${getRandomInt(1,256)}, ${getRandomInt(1,99)}, ${getRandomInt(1,256)}, 0.2)`)
    })
    let NombreMt = {{ voyageMt|raw }}
    NombreMt.forEach(mt=>{
        thirdChartBackGroundColor.push(`rgba(${getRandomInt(1,256)}, ${getRandomInt(1,99)}, ${getRandomInt(1,256)}, 0.2)`)
    })
    const ctx = document.querySelector("#voyages").getContext('2d');
    const ctx2 = document.querySelector("#stations").getContext('2d');
    const ctx3 = document.querySelector("#vehicules").getContext('2d');
    const myChart = new Chart(ctx, {
        type: 'pie',
        data: {
            labels: finalDates,
            datasets: [{
                label: 'Nombre de voyages complets',
                data: {{ finalDates|raw }},
                backgroundColor: backGroundColor,
                borderColor: backGroundColor,
                borderWidth: 1
            }]
        },
        options: {
            scales: {
                y: {

                    beginAtZero: true
                }
            },

                plugins: {
                    title: {
                        display: true,
                        text: 'Nombre de voyage par Date'
                    }
                }

        }
    });
    const stationChart = new Chart(ctx2, {
        type: 'bar',
        data: {
            labels: {{ voyageStation|raw }},
            datasets: [{
                label: 'Nombre de voyages par station',
                data: {{ finalStations|raw }},
                backgroundColor: secondChartBackGroundColor,
                borderColor: secondChartBackGroundColor,
                borderWidth: 1
            }]
        },
        options: {
            scales: {
                y: {

                    beginAtZero: true
                }
            },

            plugins: {
                title: {
                    display: true,
                    text: 'Nombre de voyage par Station'
                }
            }

        }
    });
    const MtChart = new Chart(ctx3, {
        type: 'pie',
        data: {
            labels: finalMt,
            datasets: [{
                label: 'Nombre de voyages complets',
                data: {{ finalMt|raw }},
                backgroundColor: thirdChartBackGroundColor,
                borderColor: thirdChartBackGroundColor,
                borderWidth: 1
            }]
        },
        options: {
            scales: {
                y: {

                    beginAtZero: true
                }
            },

            plugins: {
                title: {
                    display: true,
                    text: 'Nombre de voyage par Type De Moyen De Transport'
                }
            }

        }
    });
</script>
{% endblock %}