src/Entity/Station.php
<?php

namespace App\Entity;

use App\Repository\StationRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity(repositoryClass=StationRepository::class)
 *  @UniqueEntity(
 *     fields={"ref_station"},
 *     message="ref_station already exist !"
 * )
 */
class Station
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer",)
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=128,unique=true)
     * @Assert\NotBlank(message="ref_station is required")
     *
     *
     */
    private $ref_station;

    /**
     * @ORM\Column(type="string", length=128)
     * @Assert\NotBlank(message="nom_station is required")
     */
    private $nom_station;

    /**
     * @ORM\Column(type="string", length=128)
     * @Assert\NotBlank(message="position_station is required")
     */
    private $position_station;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getRefStation(): ?string
    {
        return $this->ref_station;
    }

    public function setRefStation(string $ref_station): self
    {
        $this->ref_station = $ref_station;

        return $this;
    }

    public function getNomStation(): ?string
    {
        return $this->nom_station;
    }

    public function setNomStation(string $nom_station): self
    {
        $this->nom_station = $nom_station;

        return $this;
    }

    public function getPositionStation(): ?string
    {
        return $this->position_station;
    }

    public function setPositionStation(string $position_station): self
    {
        $this->position_station = $position_station;

        return $this;
    }
    public function __toString(){
        // to show the name of the Category in the select
        return $this->getNomStation();
        // to show the id of the Category in the select
        // return $this->id;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\ORM\Mapping as ORM;
use Exception;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 */
class User implements UserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=50)
         * @Assert\Length(
         *      min = 2,
         *      max = 26,
         *      minMessage = "Your first name must be at least {{ limit }} characters long",
         *      maxMessage = "Your first name cannot be longer than {{ limit }} characters"
         * )
     */
    private $first_name;

    /**
     * @ORM\Column(type="string", length=50)
     * @Assert\Length(
     *      min = 2,
     *      max = 26,
     *      minMessage = "Your first name must be at least {{ limit }} characters long",
     *      maxMessage = "Your first name cannot be longer than {{ limit }} characters"
     * )
     *
     */
    private $last_name;

    /**
     * @ORM\Column(type="string", length=62)
     *
     */
    private $email;

    /**
     * @ORM\Column(type="integer")
     *  @Assert\Length(
     *      min=8,
     *      max = 8,
     *
     *      maxMessage = "Your number cannot be longer than {{ limit }} characters"
     * )
     */
    private $number;

    /**
     * @ORM\Column(type="string", length=150)
     *
     * @Assert\NotBlank
     *
     */
    private $username;

    /**
     * @ORM\Column(type="string", length=32)
     * @Assert\Regex(pattern="/^(?=.*[a-z])(?=.*\d).{6,}$/i", message="New password is required to be minimum 6 chars in length and to include at least one letter and one number."
     * )
     */
    private $password;

    /**
     * @ORM\Column(name="role", type="string", length=32,columnDefinition="enum('CLIENT', 'ADMIN','RESPONSABLE_ABONNEMENT','RESPONSABLE_RECLAMATION','RESPONSABLE_MDT','RESPONSABLE_VOYAGE','RESPONSABLE_RESERVATION')")
     */
    private $role;

    /**
     * @Assert\NotBlank
     * @ORM\Column(type="date")
     */
    private $birthday;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_date_user;

    /**
     * @ORM\Column(type="datetime")
     */
    private $last_updated_user;

    protected $captchaCode;

    public function getCaptchaCode()
    {
        return $this->captchaCode;
    }

    public function setCaptchaCode($captchaCode)
    {
        $this->captchaCode = $captchaCode;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstName(): ?string
    {
        return $this->first_name;
    }

    public function setFirstName(string $first_name): self
    {
        $this->first_name = $first_name;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->last_name;
    }

    public function setLastName(string $last_name): self
    {
        $this->last_name = $last_name;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getNumber(): ?int
    {
        return $this->number;
    }

    public function setNumber(int $number): self
    {
        $this->number = $number;

        return $this;
    }

    public function getUsername(): ?string
    {
        return $this->username;
    }

    public function setUsername(string $username): self
    {
        $this->username = $username;

        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    public function getRole(): ?string
    {
        return $this->role;
    }

    public function setRole(string $role): self
    {
        $this->role = $role;

        return $this;
    }

    public function getBirthday(): ?\DateTimeInterface
    {
        return $this->birthday;
    }

    public function setBirthday(\DateTimeInterface $birthday): self
    {
        $this->birthday = $birthday;

        return $this;
    }

    public function getCreatedDateUser(): ?\DateTimeInterface
    {
        return $this->created_date_user;
    }

    public function setCreatedDateUser(\DateTimeInterface $created_date_user): self
    {
        $this->created_date_user = $created_date_user;

        return $this;
    }

    public function getLastUpdatedUser(): ?\DateTimeInterface
    {
        return $this->last_updated_user;
    }

    public function setLastUpdatedUser(\DateTimeInterface $last_updated_user): self
    {
        $this->last_updated_user = $last_updated_user;

        return $this;
    }


    public function getRoles()
    {
        return array('CLIENT', 'ADMIN','RESPONSABLE_ABONNEMENT','RESPONSABLE_RECLAMATION','RESPONSABLE_MDT','RESPONSABLE_VOYAGE','RESPONSABLE_RESERVATION');
    }

    public function getSalt()
    {
        return null;
    }

    public function eraseCredentials()
    {

    }





}

src/Controller/UserController.php
<?php

namespace App\Controller;

use App\Entity\User;
use Dompdf\Dompdf;
use Dompdf\Options;
use App\Form\UserFormType;
use App\Repository\UserRepository;
use Captcha\Bundle\CaptchaBundle\Form\Type\CaptchaType;
use Captcha\Bundle\CaptchaBundle\Validator\Constraints\ValidCaptcha;
use MercurySeries\FlashyBundle\FlashyNotifier;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Http\Authentication\AuthenticationUtils;
use Symfony\Component\Validator\Constraints\DateTime;

class UserController extends AbstractController
{

    /**
     * @Route("/signup", name="signup")
     */
    public function signup(Request $request):Response
    {
        $user=new User();
        $user->setCreatedDateUser(new \DateTime());
        $user->setLastUpdatedUser(new \DateTime());
        $user->setRole("CLIENT");
        $form=$this->createFormBuilder($user)
            ->add('first_name')
            ->add('last_name')
            ->add('email')
            ->add('number')
            ->add('username')
            ->add('password',PasswordType::class)
            ->add('birthday',DateType::class)
            ->add('captchaCode', CaptchaType::class, array(
                'captchaConfig' => 'ExampleCaptchaUserRegistration',
                'constraints' => [
                    new ValidCaptcha([
                        'message' => 'Invalid captcha, please try again',
                    ]),
                ],
            ))
            ->add('signup',SubmitType::class)
            ->getForm();
        $form->handleRequest($request);
        if($form->isSubmitted() && $form->isValid()){
            $entityManager=$this->getDoctrine()->getManager();
            $entityManager->persist($user);
            $entityManager->flush();
            return $this->redirect('/');

        }
        return $this->render('user/signup.html.twig',[

            'form_user'=>$form->createView(),
        ]);
    }
    /**
     * @Route("/user", name="user")
     */
    public function user()
    {
        $users = $this->getDoctrine()->getRepository(User::class)->findAll();

        return $this->render('user/index.html.twig', [
            "users" => $users,
        ]);
    }
    /**
     * @Route("/add-user", name="add_user")
     */
    public function addUser(Request $request,FlashyNotifier $flashy): Response
    {
        $datetime = new DateTime();
        $user = new User();
        $user->setCreatedDateUser(new \DateTime());
        $user->setLastUpdatedUser(new \DateTime());
        $form=$this->createForm(UserFormType::class,$user);
        $form->handleRequest($request);
        if( $form->isSubmitted() && $form->isValid()){
            $entityManager=$this->getDoctrine()->getManager();
            $entityManager->persist($user);
            $entityManager->flush();
            $flashy->success('User Added','http://your-awesome-link.com');
            return $this->redirect('user');
        }

        return $this->render("user/_form.html.twig", [
            "form" => $form->createView(),
        ]);
    }
    /**
     * @Route("/modify-user/{id}", name="modify_user")
     */
    public function modifyUser(Request $request, int $id,FlashyNotifier $flashy): Response
    {
        $entityManager = $this->getDoctrine()->getManager();

        $user = $entityManager->getRepository(User::class)->find($id);
        $form = $this->createForm(UserFormType::class, $user);
        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid())
        {
            $entityManager->flush();
            $flashy->success('User Modified','http://your-awesome-link.com');
            return $this->redirectToRoute('user', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render("user/_form.html.twig", [
            "form_title" => "Modify user",
            "form" => $form->createView(),
        ]);
    }
    /**
     * @Route("/delete-user/{id}", name="delete_user")
     */
    public function deleteUser(int $id): Response
    {
        $entityManager = $this->getDoctrine()->getManager();
        $user = $entityManager->getRepository(User::class)->find($id);
        $entityManager->remove($user);
        $entityManager->flush();

        return $this->redirectToRoute("user");
    }

    /**
     * @Route("/imprimer/pdf", name="imprimer_index")
     */
    public function pdf(UserRepository $userRepository): Response

    {

        // Configure Dompdf according to your needs
        $pdfOptions = new Options();
        $pdfOptions->set('defaultFont', "Gill Sans MT");

        // Instantiate Dompdf with our options
        $dompdf = new Dompdf($pdfOptions);

        $user = $userRepository->findAll();

        // Retrieve the HTML generated in our twig file
        $html = $this->renderView('user/pdf.html.twig', [
            'users' =>  $user,
        ]);

        // Load HTML to Dompdf
        $dompdf->loadHtml($html);

        // (Optional) Setup the paper size and orientation 'portrait' or 'portrait'
        $dompdf->setPaper('A4', 'portrait');

        // Render the HTML as PDF
        $dompdf->render();

        // Output the generated PDF to Browser (inline view)
        $dompdf->stream("Liste user.pdf", [
            "Attachment" => true
        ]);

    }
}

templates/user/_form.html.twig
{% extends 'dashboard.html.twig' %}
{% block body %}
{% form_theme form 'bootstrap_4_horizontal_layout.html.twig' %}

{{ form_start(form,{'attr':{'novalidate':'novalidate'}}) }}
    {{ form_widget(form) }}
    {{ form_errors(form) }}
{{ form_end(form) }}
{% endblock %}

templates/user/index.html.twig
{% extends 'dashboard.html.twig' %}

{% block body %}
        <input id="search" type="text" class="form-control" placeholder="Search now" aria-label="search" aria-describedby="search">
        <a class="btn btn-primary" href="{{path('imprimer_index')}}" > Imprimer </a>
    <script src="{{ asset('Signup/vendor/jquery/jquery.min.js') }}"></script>
                <table id="tableac" class="table">
                    <thead>
                        <tr>

                            <th>ID</th>
                            <th>First Name</th>
                            <th>Last Name</th>
                            <th>Email</th>
                            <th>Number</th>
                            <th>Username</th>
                            <th>Password</th>
                            <th>Role</th>
                            <th>Birthday</th>
                            <th>Created user date</th>
                            <th>Last updated user</th>
                        </tr>
                    </thead>
                    <tbody>
                    {% for user in users %}
                        <tr>

                            <td>{{ user.id }}</td>
                            <td>{{ user.getFirstName() }}</td>
                            <td>{{ user.getLastName() }}</td>
                            <td>{{ user.getEmail() }}</td>
                            <td>{{ user.getNumber() }}</td>
                            <td>{{ user.getUsername() }}</td>
                            <td>{{ user.getPassword() }}</td>
                            <td>{{ user.getRole() }}</td>
                            <td>{{ user.getBirthday()|date("m/d/Y") }}</td>
                            <td>{{ user.getCreatedDateUser()|date('Y-m-d H:i:s') }}</td>
                            <td>{{ user.getLastUpdatedUser()|date('Y-m-d H:i:s') }}</td>
                            <td>
                                <a class="btn btn-primary" href="{{ path('delete_user', {'id': user.id}) }}">delete</a>
                                <a class="btn btn-danger" href="{{ path('modify_user', {'id': user.id}) }}">edit</a>
                            </td>
                        </tr>
                    {% else %}
                        <tr>
                            <td colspan="6">no records found</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
    <a class="btn btn-warning" href="{{ path('add_user') }}">Create new</a>

    <script>
        $(document).ready(function(){
            $('#search').keyup(function(){
                search_table($(this).val());
            });
            function search_table(value){
                $('#tableac tbody tr').each(function(){
                    var found = 'false';
                    $(this).each(function(){
                        if($(this).text().toLowerCase().indexOf(value.toLowerCase()) >= 0)
                        {
                            found = 'true';
                        }
                    });
                    if(found == 'true')
                    {
                        $(this).show();

                    }
                    else
                    {
                        $(this).hide();

                    }
                });
            }
        });
    </script>
{% endblock %}

templates/user/login.html.twig
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Login V5</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!--===============================================================================================-->
    <link rel="icon" type="image/png" href="{{ asset("login/images/icons/favicon.ico") }}"/>
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{{ asset("login/vendor/bootstrap/css/bootstrap.min.css") }}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{{ asset("login/fonts/font-awesome-4.7.0/css/font-awesome.min.css") }}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{{ asset("login/fonts/Linearicons-Free-v1.0.0/icon-font.min.css") }}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{{ asset("login/vendor/animate/animate.css") }}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{{ asset("login/vendor/css-hamburgers/hamburgers.min.css") }}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{{ asset("login/vendor/animsition/css/animsition.min.css") }}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{{ asset("login/vendor/select2/select2.min.css") }}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{{ asset("login/vendor/daterangepicker/daterangepicker.css") }}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{{ asset("login/css/util.css") }}">
    <link rel="stylesheet" type="text/css" href="{{ asset("login/css/main.css") }}">
    <!--===============================================================================================-->
</head>
<body>

<div class="limiter">
    <div class="container-login100">
        <div class="wrap-login100 p-l-110 p-r-110 p-t-62 p-b-33">
            {% if error %}
                <div class="alert alert-danger">
                    {{ error.messageKey }}
                </div>
            {% endif %}
            <form class="login100-form validate-form flex-sb flex-w" action="{{ path('login') }}" method="POST">
					<span class="login100-form-title p-b-53">
						Sign In With
					</span>

                <a href="#" class="btn-face m-b-20">
                    <i class="fa fa-facebook-official"></i>
                    Facebook
                </a>

                <a href="#" class="btn-google m-b-20">
                    <img src="{{ asset("login/images/icons/icon-google.png") }}" alt="GOOGLE">
                    Google
                </a>

                <div class="p-t-31 p-b-9">
						<span class="txt1">
							Username
						</span>
                </div>
                <div class="wrap-input100 validate-input" data-validate = "Username is required">

                    <!-- {d{ form_widget(form.username,{ 'attr': {'class': 'input100'} }) }} -->
                    <input type="text" id="username" name="_username" class="input100" value="{{ last_username }}">

                    <span class="focus-input100"></span>
                </div>

                <div class="p-t-13 p-b-9">
						<span class="txt1">
							Password
						</span>

                    <a href="#" class="txt2 bo1 m-l-5">
                        Forgot?
                    </a>
                </div>
                <div class="wrap-input100 validate-input" data-validate = "Password is required">
                    <!--{d{ form_widget(form.password,{ 'attr': {'class': 'input100'} }) }}-->
                    <input type="password" id="password" name="_password" class="input100">
                    <span class="focus-input100"></span>
                </div>

                <div class="container-login100-form-btn m-t-17">
                    <input type="submit" value="Login" class="login100-form-btn">


                </div>

                <div class="w-full text-center p-t-55">
						<span class="txt2">
							Not a member?
						</span>

                    <a href="#" class="txt2 bo1">
                        Sign up now
                    </a>
                </div>

            </form>
        </div>
    </div>
</div>


<div id="dropDownSelect1"></div>

<!--===============================================================================================-->
<script src="vendor/jquery/jquery-3.2.1.min.js"></script>
<!--===============================================================================================-->
<script src="vendor/animsition/js/animsition.min.js"></script>
<!--===============================================================================================-->
<script src="vendor/bootstrap/js/popper.js"></script>
<script src="vendor/bootstrap/js/bootstrap.min.js"></script>
<!--===============================================================================================-->
<script src="vendor/select2/select2.min.js"></script>
<!--===============================================================================================-->
<script src="vendor/daterangepicker/moment.min.js"></script>
<script src="vendor/daterangepicker/daterangepicker.js"></script>
<!--===============================================================================================-->
<script src="vendor/countdowntime/countdowntime.js"></script>
<!--===============================================================================================-->
<script src="js/main.js"></script>

</body>
</html>

templates/user/pdf.html.twig
{% block body %}
    <h1 align ="center" style="color:green;">Liste des Utilisateurs</h1><hr>
    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-header card-header-primary">
                            <h1 align="center" style="color:blue;">Utilisateurs</h1>

                        </div>
                            <style>
                                #customers {
                                    font-family: Arial, Helvetica, sans-serif;
                                    border-collapse: collapse;
                                    width: 20%;
                                }
                                #customers td, #customers th {
                                    border: 1px solid #ddd;
                                    padding: -1px;
                                }
                                #customers tr:nth-child(even){background-color: #f2f2f2;}
                                #customers tr:hover {background-color: #ddd;}
                                #customers th {
                                    padding-top: -1px;
                                    padding-bottom: -1px;
                                    text-align: left;
                                    background-color: royalblue;
                                    color: white;
                                }
                            </style>
                    </div>
                </div>
            </div>
        </div>
    </div>


    <table class="table table-striped table-bordered" id="customers" >
        <thead>
        <tr>

            <th class="wd-15p">ID</th>
            <th class="wd-15p">First Name</th>
            <th class="wd-15p">Last Name</th>
            <th class="wd-15p">Email</th>
            <th class="wd-15p">Number</th>
            <th class="wd-15p">Username</th>
            <th class="wd-15p">Password</th>
            <th class="wd-15p">Role</th>
            <th class="wd-15p">Birthday</th>
            <th class="wd-15p">Created user date</th>
            <th class="wd-15p">Last updated user</th>
        </tr>
        </thead>
        <tbody>
        {% for user in users %}
            <tr>

                <td>{{ user.id }}</td>
                <td>{{ user.getFirstName() }}</td>
                <td>{{ user.getLastName() }}</td>
                <td>{{ user.getEmail() }}</td>
                <td>{{ user.getNumber() }}</td>
                <td>{{ user.getUsername() }}</td>
                <td>{{ user.getPassword() }}</td>
                <td>{{ user.getRole() }}</td>
                <td>{{ user.getBirthday()|date("m/d/Y") }}</td>
                <td>{{ user.getCreatedDateUser()|date('Y-m-d H:i:s') }}</td>
                <td>{{ user.getLastUpdatedUser()|date('Y-m-d H:i:s') }}</td>
                <td>
                    <a class="btn btn-primary" href="{{ path('delete_user', {'id': user.id}) }}">delete</a>
                    <a class="btn btn-danger" href="{{ path('modify_user', {'id': user.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>


{% endblock %}

templates/user/show.html.twig
{% extends 'dashboard.html.twig' %}

{% block title %}Station{% endblock %}

{% block body %}
    <h1>Station</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ station.id }}</td>
            </tr>
            <tr>
                <th>Ref_station</th>
                <td>{{ station.refStation }}</td>
            </tr>
            <tr>
                <th>Nom_station</th>
                <td>{{ station.nomStation }}</td>
            </tr>
            <tr>
                <th>Position_station</th>
                <td>{{ station.positionStation }}</td>
            </tr>
        </tbody>
    </table>
    <div class="d-grid gap-2 d-md-block">
        <a class="btn btn-primary" href="{{ path('station_index') }}">back to list</a>
        <a class="btn btn-warning" href="{{ path('station_edit', {'id': station.id}) }}">edit</a>
        {{ include('station/_delete_form.html.twig') }}
    </div>



{% endblock %}

templates/user/stat.html.twig
{% extends 'dashboard.html.twig' %}

{% block title %} Statistiques{% endblock %}
{% block stylesheets %}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.4/Chart.min.css" integrity="sha512-/zs32ZEJh+/EO2N1b0PEdoA10JkdC3zJ8L5FTiQu82LR9S/rOQNfQN7U59U9BC12swNeRAz3HSzIL2vpp4fv3w==" crossorigin="anonymous" referrerpolicy="no-referrer" />
{% endblock %}
{% block body %}
    <div class="container" style="width: 600px !important; height: 480px !important;">
        <h1>Statistiques Pour Le Module User</h1>
        <canvas id="users" width="100" height="100" style="margin-top :50px !important;"></canvas>
        <canvas id="roles" width="100" height="100" style="margin-top :50px !important;"></canvas>
        <canvas id="vehicules" width="100" height="100" style="margin-top :50px !important;"></canvas>
    </div>



{% endblock %}
{% block javascripts %}
    <script src="https://cdn.jsdelivr.net/npm/chart.js@3.6.1/dist/chart.min.js"></script>
    <script>

        const dates = {{ userCreatedDate|raw }}
        const newDates = [];
        dates.forEach(date=>{
            newDates.push(date.date.split(" ")[0]);
        })
        const finalDates = [...new Set(newDates)]

        //set the color of bars dynamically
        let backGroundColor = [];
        function getRandomInt(min, max) {
            min = Math.ceil(min);
            max = Math.floor(max);
            return Math.floor(Math.random() * (max - min + 1)) + min;
        }
        //we need to get the exact number of dates
        finalDates.forEach(date=>{
            //set random rgb values for each date
            backGroundColor.push(`rgba(${getRandomInt(1,256)}, ${getRandomInt(1,99)}, ${getRandomInt(1,256)}, 0.2)`)
        })
        let secondChartBackGroundColor = []
        let thirdChartBackGroundColor = []

        let NombreRoles = {{ role|raw }} ;
        NombreRoles.forEach(role=>{
            secondChartBackGroundColor.push(`rgba(${getRandomInt(1,256)}, ${getRandomInt(1,99)}, ${getRandomInt(1,256)}, 0.2)`)
        })

        const ctx = document.querySelector("#users").getContext('2d');
        const ctx2 = document.querySelector("#roles").getContext('2d');
        const ctx3 = document.querySelector("#vehicules").getContext('2d');
        const myChart = new Chart(ctx, {
            type: 'pie',
            data: {
                labels: finalDates,
                datasets: [{
                    label: 'Nombre de user complets',
                    data: {{ finalDates|raw }},
                    backgroundColor: backGroundColor,
                    borderColor: backGroundColor,
                    borderWidth: 1
                }]
            },
            options: {
                scales: {
                    y: {

                        beginAtZero: true
                    }
                },

                plugins: {
                    title: {
                        display: true,
                        text: 'Nombre de user par Date de Creation'
                    }
                }

            }
        });
        const stationChart = new Chart(ctx2, {
            type: 'bar',
            data: {
                labels: {{ role|raw }},
                datasets: [{
                    label: 'Nombre de user par role',
                    data: {{ finalroles|raw }},
                    backgroundColor: secondChartBackGroundColor,
                    borderColor: secondChartBackGroundColor,
                    borderWidth: 1
                }]
            },
            options: {
                scales: {
                    y: {

                        beginAtZero: true
                    }
                },

                plugins: {
                    title: {
                        display: true,
                        text: 'Nombre de User par Role'
                    }
                }

            }
        });

    </script>
{% endblock %}